### ISSUE TITLE
Unable to find any test documents

### ISSUE THREAD

**Issue by syatom** [zuvaai/docai-examples#5]
Are there any test documents that we can use for testing using the provided examples.

**Comment by matt-cote** [comment]
Hi again @syatom, there are some test documents available in this repository here: https://github.com/zuvaai/docai-examples/tree/main/python-sdk/training/upload_files

You can also download the [Zuva_Sample_Documents.zip](https://github.com/zuvaai/zdai-postman) file which contains another collections of sample documents.

**Comment by syatom** [comment]
Thanks for the links.
