### ISSUE TITLE
ocr http request method not allowed

### ISSUE THREAD

**Issue by syatom** [zuvaai/docai-examples#6]
I am using your example code provided and when I upload a pdf it fails with an error 405 Method Not Allowed.

Do I need to set up anything for the ocr to work?

![image](https://github.com/zuvaai/docai-examples/assets/53854902/729a654e-7bac-4338-aa53-835d45fbf2d5)
![image](https://github.com/zuvaai/docai-examples/assets/53854902/53ccfd28-73f8-472b-a725-d04638b709e8)
![image](https://github.com/zuvaai/docai-examples/assets/53854902/82eccc86-992b-4b63-9b45-b58fe8902b99)

**Comment by matt-cote** [comment]
Hi @syatom, the OCR endpoints are not available with the free plan. I spoke with our team and they informed me that the company you are working with has signed up for a trial which does include access to this feature. Please check with your team as they will be able to create a new token which will allow you to use the OCR endpoints required for this tutorial.

**Comment by syatom** [comment]
We created a new token and still getting the same issue.
![image](https://github.com/zuvaai/docai-examples/assets/53854902/3b150365-c944-4579-b4c8-a1c2426e6252)
![image](https://github.com/zuvaai/docai-examples/assets/53854902/b7700941-a995-4ca4-8643-e87d4c28e6fe)
![image](https://github.com/zuvaai/docai-examples/assets/53854902/e1cfff60-048b-4cb6-8f57-48b3b3dd9bba)

**Comment by matt-cote** [comment]
It looks like your account was still flagged as free in our Europe region. I have updated this for you now, please try again at your convenience. Thanks

**Comment by syatom** [comment]
Great thanks all working now :-)
